### ISSUE TITLE
Pull changes from kvm-bindings upstream

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/kvm-bindings#11]
We released kvm-bindings v0.4.0. The version of the fork should also be updated so that we can use the newest kvm-ioctls version in Firecracker.

**Comment by andreeaflorescu** [comment]
Commit that needs to be ported: https://github.com/rust-vmm/kvm-bindings/pull/33/commits/581b3b769ff34ce8a50613c3532a34daf860b121

**Comment by alindima** [comment]
Done in https://github.com/firecracker-microvm/kvm-bindings/pull/12
